server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ebornier-pivotal/CloudNativeTour-config.git
          #searchPaths: config-repo # if you need a subfolder 
