spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  sleuth:
    sampler:
      probability: 1

security:
  basic:
    enabled: false
  ignored: /**
    

---

spring:
  profiles: default
  jpa:
    database: HSQL

---

spring:
  profiles: cloud
#  jpa:
#    database: POSTGRESQL
#     database: HSQL
