server:
  port: 8081

#eureka:
 # client:
  #  registryFetchIntervalSeconds: 5

#fortunes:
 # ribbon:
  #  ServerListRefreshInterval: 5000

spring:
  sleuth:
    sampler:
      probability: 1

security:
  basic:
    enabled: false

---


